import "./setup.js";
import {readFileSync} from "node:fs";
import {resolve} from "node:path";
import "../../../js/charactersheet/charactersheet-state.js";
import "../../../js/charactersheet/charactersheet-combat.js";

const CharacterSheetState = globalThis.CharacterSheetState;
const CharacterSheetCombat = globalThis.CharacterSheetCombat;

const makeAttack = (overrides = {}) => ({
	id: "attack-1",
	name: "Longsword",
	damage: "1d8",
	damageType: "slashing",
	damageBonus: 1,
	isMelee: true,
	abilityMod: "str",
	...overrides,
});

describe("standing weapon damage bonus contract", () => {
	let state;

	beforeEach(() => {
		state = new CharacterSheetState();
		state.setAbilityBase("str", 16);
	});

	test("includes unconditional numeric feature and active-state flat damage", () => {
		state.addNamedModifier({name: "Weapon Training", type: "damage", value: 2});
		state.addActiveState("custom", {
			name: "Battle Trance",
			customEffects: [{type: "bonus", target: "damage", value: 3}],
		});

		const breakdown = state.getWeaponDisplayDamageBreakdown(makeAttack());

		expect(breakdown).toMatchObject({base: 1, feature: 2, state: 3, total: 6});
		expect(state.getWeaponDisplayDamageBonus(makeAttack())).toBe(6);
	});

	test("includes matching weapon-scoped item damage", () => {
		state.addItem({
			name: "Bracers of Archery",
			source: "DMG",
			wondrous: true,
			requiresAttunement: true,
			bonusWeaponDamage: 2,
			equipped: true,
			attuned: true,
			_isCustom: true,
		});
		const attack = makeAttack({
			name: "Longbow",
			damage: "1d8",
			damageType: "piercing",
			isMelee: false,
			isRanged: true,
			abilityMod: "dex",
			sourceItem: {name: "Longbow", baseItem: null},
		});

		expect(state.getWeaponDisplayDamageBreakdown(attack)).toMatchObject({
			base: 1,
			item: 2,
			itemContributions: [{name: "Bracers of Archery", value: 2}],
			total: 3,
		});
	});

	test("includes active Rage only for melee attacks actually using Strength", () => {
		state.addClass({name: "Barbarian", source: "PHB", level: 1});
		state.addActiveState("rage");

		expect(state.getWeaponDisplayDamageBreakdown(makeAttack()).rage).toBe(2);
		expect(state.getWeaponDisplayDamageBonus(makeAttack())).toBe(3);
		expect(state.getWeaponDisplayDamageBreakdown(makeAttack({isMelee: false, isRanged: true})).rage).toBe(0);
		expect(state.getWeaponDisplayDamageBreakdown(makeAttack({abilityMod: "dex"})).rage).toBe(0);
	});

	test("includes Hybrid Transformation only for melee weapon attacks", () => {
		state.isStateTypeActive = stateTypeId => stateTypeId === "hybridTransformation";
		state.getFeatureCalculation = key => key === "hybridDamageBonus" ? 2 : null;

		expect(state.getWeaponDisplayDamageBreakdown(makeAttack()).hybrid).toBe(2);
		expect(state.getWeaponDisplayDamageBreakdown(makeAttack({isMelee: false, isRanged: true})).hybrid).toBe(0);
		expect(state.getWeaponDisplayDamageBreakdown(makeAttack({isMelee: undefined, range: "20/60 ft."})).hybrid).toBe(0);
	});

	test("excludes conditional, critical, manual, once-per-turn, and dice modifiers", () => {
		state._data.namedModifiers.push(
			{name: "Always On", type: "damage", value: 2, enabled: true},
			{name: "Vs Dragons", type: "damage", value: 9, conditional: "against dragons", enabled: true},
			{name: "Critical Edge", type: "damage", value: 7, critOnly: true, enabled: true},
			{name: "Manual Smite", type: "damage", value: 6, manual: true, enabled: true},
			{name: "Once Per Turn", type: "damage", value: 5, oncePerTurn: true, enabled: true},
			{name: "Dice Rider", type: "damage", value: "1d6", enabled: true},
		);

		expect(state.getWeaponDisplayDamageBreakdown(makeAttack())).toMatchObject({
			base: 1,
			feature: 2,
			total: 3,
		});
	});

	test.each([
		["auto-generated", makeAttack({
			id: "auto-magic-sword",
			isAutoGenerated: true,
			damageBonus: 3,
			sourceItem: {name: "Magic Sword", bonusWeapon: 2, bonusWeaponDamage: 1},
		})],
		["custom", makeAttack({
			id: "custom-magic-sword",
			damageBonus: 3,
			sourceItem: {name: "Magic Sword", bonusWeapon: 2, bonusWeaponDamage: 1},
		})],
	])("counts the %s attack's authoritative base exactly once", (label, attack) => {
		expect(state.getWeaponDisplayDamageBreakdown(attack)).toMatchObject({base: 3, total: 3});
	});
});

describe("display and roll consumers", () => {
	test("Combat, Overview, and Play Mode read the shared standing bonus", () => {
		const root = process.cwd();
		const combatSource = readFileSync(resolve(root, "js/charactersheet/charactersheet-combat.js"), "utf8");
		const overviewSource = readFileSync(resolve(root, "js/charactersheet/charactersheet.js"), "utf8");
		const playModeSource = readFileSync(resolve(root, "js/charactersheet/charactersheet-playmode.js"), "utf8");

		expect(combatSource).toMatch(/totalDamageBonus = abilityMod \+ \(this\._state\.getWeaponDisplayDamageBonus\?\.\(attack\)/);
		expect(overviewSource).toMatch(/totalDamageBonus = abilityMod \+ \(this\._state\.getWeaponDisplayDamageBonus\?\.\(attack\)/);
		expect(playModeSource).toMatch(/totalDmgBonus = abilityMod \+ \(this\._state\.getWeaponDisplayDamageBonus\?\.\(attack\)/);
	});

	test("_rollDamage uses the shared standing total", async () => {
		const attack = makeAttack();
		const combat = Object.create(CharacterSheetCombat.prototype);
		let shown;
		combat._state = {
			getAttacks: () => [attack],
			getWeaponAbilityMod: () => 3,
			getWeaponDisplayDamageBreakdown: () => ({
				base: 1,
				feature: 2,
				itemContributions: [{name: "Scoped Item", value: 3}],
				item: 3,
				state: 1,
				rage: 2,
				hybrid: 0,
				total: 9,
			}),
			getFeatureCalculations: () => ({}),
		};
		combat._page = {
			showDiceResult: payload => { shown = payload; },
			pAnimateDamageDice: () => {},
		};
		combat._parseDamage = () => ({total: 5, sides: 8, rolls: [5]});
		combat._canApplySneakAttack = () => false;
		combat._resolveChannelRiderDamage = () => ({channelSpell: null, channelSpellRoll: null, channelSpellDamage: 0, riderMatched: false});
		combat._promptUseCombatMethod = async () => null;

		await combat._rollDamage(attack.id);

		expect(shown.modifier).toBe(12);
		expect(shown.subtitle).toContain("+ 2 (features)");
		expect(shown.subtitle).toContain("+ 3 (Scoped Item)");
		expect(shown.subtitle).toContain("+ 2 (rage)");
		expect(shown.subtitle).toContain("+ 1 (states)");
	});
});
