import "./setup.js";
import {jest} from "@jest/globals";
import "../../../js/charactersheet/charactersheet-class-utils.js";
import "../../../js/charactersheet/charactersheet-state.js";
import "../../../js/charactersheet/charactersheet-combat.js";

const CharacterSheetCombat = globalThis.CharacterSheetCombat;
const CharacterSheetState = globalThis.CharacterSheetState;

function makeCombat (state) {
	const saveCharacter = jest.fn();
	const combat = Object.create(CharacterSheetCombat.prototype);
	combat._state = state;
	combat._page = {_saveCurrentCharacter: saveCharacter};
	combat.renderAttacks = jest.fn();
	combat._cachedAttacks = [];
	return {combat, saveCharacter};
}

function addEquippedWeapon (state, overrides = undefined) {
	const id = "weapon-longsword";
	state.addItem({
		id,
		name: "Longsword",
		source: "PHB",
		type: "M",
		weapon: true,
		dmg1: "1d8",
		dmgType: "S",
		property: [],
		...(overrides ? {attackOverrides: overrides} : {}),
	}, 1, true);
	return id;
}

describe("CharacterSheetCombat attack notes", () => {
	let state;
	let combat;
	let saveCharacter;

	beforeEach(() => {
		state = new CharacterSheetState();
		({combat, saveCharacter} = makeCombat(state));
	});

	test("manual attack notes can be added, changed, cleared, rerendered, and saved", () => {
		state.addAttack({id: "manual-sling", name: "Pocket Sling", damage: "1d4", damageType: "bludgeoning"});

		expect(combat._saveAttackNote("manual-sling", "First note")).toBe(true);
		expect(combat._getAttackNote("manual-sling")).toBe("First note");
		expect(combat._saveAttackNote("manual-sling", "Changed note")).toBe(true);
		expect(combat._getAttackNote("manual-sling")).toBe("Changed note");
		expect(combat._saveAttackNote("manual-sling", "")).toBe(true);
		expect(combat._getAttackNote("manual-sling")).toBe("");
		expect(combat.renderAttacks).toHaveBeenCalledTimes(3);
		expect(saveCharacter).toHaveBeenCalledTimes(3);
	});

	test("generated weapon attack notes use the cached attack and backing item override", () => {
		const itemId = addEquippedWeapon(state, {abilityMod: "dex"});
		const sourceItem = state.getItems().find(item => item.id === itemId);
		combat._cachedAttacks = [{
			id: `auto_${itemId}`,
			name: "Longsword",
			isAutoGenerated: true,
			sourceItem,
		}];

		expect(combat._saveAttackNote(`auto_${itemId}`, "Use against armored foes")).toBe(true);
		expect(combat._getAttackNote(`auto_${itemId}`)).toBe("Use against armored foes");
		expect(state.getItemRaw(itemId).attackOverrides).toEqual({
			abilityMod: "dex",
			note: "Use against armored foes",
		});

		expect(combat._saveAttackNote(`auto_${itemId}`, "Changed")).toBe(true);
		expect(state.getItemRaw(itemId).attackOverrides.note).toBe("Changed");

		expect(combat._saveAttackNote(`auto_${itemId}`, "")).toBe(true);
		expect(state.getItemRaw(itemId).attackOverrides).toEqual({abilityMod: "dex"});
		expect(combat.renderAttacks).toHaveBeenCalledTimes(3);
		expect(saveCharacter).toHaveBeenCalledTimes(3);
	});

	test("generated note-only overrides are removed cleanly when the note is cleared", () => {
		const itemId = addEquippedWeapon(state);
		const sourceItem = state.getItems().find(item => item.id === itemId);
		combat._cachedAttacks = [{id: `auto_${itemId}`, name: "Longsword", isAutoGenerated: true, sourceItem}];

		combat._saveAttackNote(`auto_${itemId}`, "Temporary reminder");
		expect(state.getItemRaw(itemId).attackOverrides).toEqual({note: "Temporary reminder"});

		combat._saveAttackNote(`auto_${itemId}`, "");
		expect(state.getItemRaw(itemId).attackOverrides).toBeUndefined();
	});

	test("weapon attack override save and reset preserve an existing generated note", () => {
		const itemId = addEquippedWeapon(state, {abilityMod: "str", note: "Keep this"});

		expect(combat._persistWeaponAttackOverrides(itemId, {
			attackOverrides: {abilityMod: "dex", damage: "1d10"},
			customAttackBonus: 2,
		})).toBe(true);
		expect(state.getItemRaw(itemId).attackOverrides).toEqual({
			abilityMod: "dex",
			damage: "1d10",
			note: "Keep this",
		});

		expect(combat._persistWeaponAttackOverrides(itemId, {
			attackOverrides: null,
			customAttackBonus: null,
			customDamageBonus: null,
		})).toBe(true);
		expect(state.getItemRaw(itemId).attackOverrides).toEqual({note: "Keep this"});
	});

	test("generated attack notes survive a save/load round trip and a rebuilt cache", () => {
		const itemId = addEquippedWeapon(state);
		combat._cachedAttacks = [{
			id: `auto_${itemId}`,
			name: "Longsword",
			isAutoGenerated: true,
			sourceItem: state.getItems().find(item => item.id === itemId),
		}];
		combat._saveAttackNote(`auto_${itemId}`, "Persistent note");

		const loaded = new CharacterSheetState();
		loaded.loadFromJson(state.serialize());
		const {combat: reloadedCombat} = makeCombat(loaded);
		reloadedCombat._cachedAttacks = [{
			id: `auto_${itemId}`,
			name: "Longsword",
			isAutoGenerated: true,
			sourceItem: loaded.getItems().find(item => item.id === itemId),
		}];

		expect(reloadedCombat._getAttackNote(`auto_${itemId}`)).toBe("Persistent note");
	});

	test("rendered note controls reflect durable storage and persisted generated notes", () => {
		const itemId = addEquippedWeapon(state, {note: "Persistent note"});
		const generated = {
			id: `auto_${itemId}`,
			name: "Longsword",
			damage: "1d8",
			damageType: "slashing",
			mastery: [],
			isAutoGenerated: true,
			sourceItem: state.getItems().find(item => item.id === itemId),
		};
		const temporary = {
			id: "temp-attack",
			name: "Temporary",
			damage: "1d6",
			damageType: "force",
			mastery: [],
			isTemporary: true,
		};
		combat._state = {
			...state,
			getAttacks: () => [],
			getItemRaw: id => state.getItemRaw(id),
			getItems: () => state.getItems(),
			getWeaponAbilityMod: () => 3,
			getProficiencyBonus: () => 2,
			getAttackModifierContributions: () => [],
			getBonusFromStates: () => 0,
			getCriticalRange: () => 20,
			getActiveCombatMethodEffects: () => [],
			getClassLevel: () => 0,
			getAttackRiderNotes: () => [],
		};
		combat._getAttackRollKind = () => ({isMelee: true});
		combat._buildAttackRangeDisplay = () => ({rangeHtml: ""});
		combat._renderHandsUsedToggle = () => "";
		combat._renderAmmoSelector = () => "";
		combat._renderChannelSpellButton = () => "";
		combat._getAttackPenetrationHtml = () => "";
		combat._formatProperty = () => "";
		combat._formatMasteryLink = () => "";

		const generatedHtml = combat._renderAttackItem(generated).outerHTML;
		const temporaryHtml = combat._renderAttackItem(temporary).outerHTML;

		expect(generatedHtml).toMatch(/ve-btn-warning[^"]*charsheet__attack-note/);
		expect(temporaryHtml).not.toContain("charsheet__attack-note");
	});

	test.each([
		[{id: "temp-attack", name: "Temporary", isTemporary: true}, "temporary"],
		[{id: "feature-attack", name: "Feature", isFeatureAttack: true}, "feature-granted"],
		[{id: "state-attack", name: "State", isActiveStateAttack: true}, "active-state"],
	])("%s attacks without durable backing storage do not expose note persistence", (attack) => {
		if (attack.isTemporary) state.getTemporaryAttacks = () => [attack];
		else if (attack.isActiveStateAttack) state.getActiveStateAttacks = () => [attack];
		else combat._cachedAttacks = [attack];

		expect(combat._resolveAttackNoteStorage(attack.id)).toMatchObject({attack, storage: null});
		expect(combat._saveAttackNote(attack.id, "Cannot persist")).toBe(false);
		expect(saveCharacter).not.toHaveBeenCalled();
	});
});
