import {expect, test} from "@playwright/test";
import {EncounterRollPage} from "../pages/EncounterRollPage";

test("effective-statblock roster group exposes mixed selection, collapse and independent member state", async ({page}) => {
	await new EncounterRollPage(page).seed();
	const group = page.locator(".ew__roster-group").first();
	await expect(page.locator(".ew__group-header")).toHaveCount(1);
	await expect(group.locator(".ew__group-title")).toContainText("Goblin ×2");
	await expect(page.locator(".ew__statblock")).toHaveCount(2);
	const groupCheck = group.locator(".ew__group-header input[type=checkbox]");
	await expect(groupCheck).toHaveJSProperty("indeterminate", true);
	await group.getByRole("button", {name: /Collapse.*group/}).click();
	await expect(group.locator(".ew__group-members")).toBeHidden();
	await groupCheck.check();
	await expect(page.locator("#ew-summary")).toContainText("2 of 2 selected");
	await expect(groupCheck).toHaveJSProperty("indeterminate", false);
	await group.getByRole("button", {name: /Expand.*group/}).click();
	await expect(group.locator(".ew__roster-row")).toHaveCount(2);
	await group.locator(".ew__roster-row input[type=checkbox]").last().uncheck();
	await expect(groupCheck).toHaveJSProperty("indeterminate", true);
	await expect(page.locator("#ew-summary")).toContainText("1 of 2 selected");
	await page.locator(".ew__statblock").last().locator("[data-field=current]").fill("3");
	await page.locator(".ew__statblock").last().locator("[data-field=current]").press("Tab");
	await expect(group.locator(".ew__roster-meta").first()).toContainText("HP 7/7");
	await expect(group.locator(".ew__roster-meta").last()).toContainText("HP 3/7");
});

test("a confirmed shared initiative acts once, survives reload, and restores original totals", async ({page}) => {
	await new EncounterRollPage(page).seed();
	const group = page.locator(".ew__roster-group").first();
	await page.locator(".ew__statblock").first().locator("[data-field=initiative]").fill("9");
	await page.locator(".ew__statblock").first().locator("[data-field=initiative]").press("Tab");
	await expect(page.locator("#ew-status")).toContainText("to 9");
	await page.locator(".ew__statblock").last().locator("[data-field=initiative]").fill("20");
	await page.locator(".ew__statblock").last().locator("[data-field=initiative]").press("Tab");
	await expect(page.locator("#ew-status")).toContainText("to 20");
	await group.locator(".ew__group-init").fill("16");
	await group.getByRole("button", {name: "Share turns"}).click();
	await expect(page.getByText(/individual totals \(9, 20\)/)).toBeVisible();
	await page.getByRole("button", {name: /Share turn$/}).click();
	await expect(page.locator(".ew__turn")).toHaveCount(1);
	await expect(page.locator(".ew__turn")).toContainText("16");
	await page.locator("#ew-turn-start").click();
	await expect(page.locator("#ew-round-status")).toContainText("Round 1");
	await page.locator("#ew-turn-next").click();
	await expect(page.locator("#ew-round-status")).toContainText("Round 2");
	await expect(page.locator(".ew__turn")).toHaveCount(1);
	await group.locator(".ew__group-init").fill("18");
	await group.locator(".ew__group-init").press("Tab");
	await expect(page.locator(".ew__turn")).toContainText("18");
	await page.reload();
	await expect(page.locator("#encounter-workspace")).toHaveAttribute("aria-busy", "false");
	await expect(page.locator(".ew__group-init")).toHaveValue("18");
	await expect(page.locator("#ew-round-status")).toContainText("Round 2");
	await expect(page.locator(".ew__statblock [data-field=initiative]").first()).toBeDisabled();
	await page.locator("#ew-all").click();
	await page.locator("#ew-init-roll").click();
	await expect(page.locator("#ew-result-table tbody tr")).toHaveCount(1);
	await expect(page.locator(".ew__turn")).toHaveCount(1);
	await page.getByRole("button", {name: "Individual turns"}).click();
	await expect(page.locator(".ew__turn")).toHaveCount(2);
	await expect(page.locator(".ew__statblock [data-field=initiative]").first()).toHaveValue("9");
	await expect(page.locator(".ew__statblock [data-field=initiative]").last()).toHaveValue("20");
	await expect(page.locator("#ew-round-status")).toContainText("Goblin #1");
});

test("create, split, rejoin and disband controls persist deliberate separation", async ({page}) => {
	await new EncounterRollPage(page).seed();
	await page.locator("#ew-all").click();
	await page.locator("#ew-group-selected").click();
	await expect(page.locator("#ew-status")).toContainText("Created a persistent group");
	await expect(page.locator(".ew__group-title")).toContainText("Goblin ×2");
	await page.locator(".ew__roster-row").last().getByRole("button", {name: /Split Goblin #2/}).click();
	await expect(page.locator(".ew__group-title")).toContainText("Goblin ×1");
	await page.locator(".ew__roster-row").last().getByRole("button", {name: /Rejoin Goblin #2/}).click();
	await expect(page.locator(".ew__group-title")).toContainText("Goblin ×2");
	await page.getByRole("button", {name: "Disband"}).click();
	await expect(page.locator(".ew__group-header")).toHaveCount(0);
	await page.reload();
	await expect(page.locator("#encounter-workspace")).toHaveAttribute("aria-busy", "false");
	await expect(page.locator(".ew__group-header")).toHaveCount(0);
	await page.locator(".ew__roster-row").first().getByRole("button", {name: /Rejoin Goblin #1/}).click();
	await page.locator(".ew__roster-row").last().getByRole("button", {name: /Rejoin Goblin #2/}).click();
	await expect(page.locator(".ew__group-title")).toContainText("Goblin ×2");
	await page.setViewportSize({width: 390, height: 844});
	const roster = page.locator("#ew-roster");
	await expect(roster).toBeVisible();
	expect(await roster.evaluate(element => element.scrollWidth <= element.clientWidth + 2)).toBe(true);
});
