import {describeCharacter} from "../utils/characterSpecFactory";
import {PRESET_FULL_TIME_CLERIC} from "../utils/characterBuilder";

describeCharacter({
	displayName: "Time Domain Cleric (TGTT)",
	preset: {
		...PRESET_FULL_TIME_CLERIC,
		abilityPriority: ["wis", "con", "dex", "str", "int", "cha"],
		signatureSpells: ["Sacred Flame", "Guidance", "Cure Wounds"],
	},
	midTierLoadout: [
		{name: "Mace", equipped: true},
		{name: "Shield", equipped: true},
	],
	usage: {
		atLevel: 5,
		castSpellSlotLevel: 1,
		useResourceName: "Channel Divinity",
		expectLongRestRestores: true,
		attackName: /mace/i,
		skillRoll: {name: "Religion"},
		shortRestRestores: {resourceName: "Channel Divinity", spend: 2, expectAfter: 1},
		concentrationCheck: {castSpell: "Bless", thenAction: "damage", expectActive: false},
		deathSaves: true,
		applyCondition: {name: "Restrained"},
		featAbility: {skip: true},
	},
	milestones: {
		1: {totalLevel: 1, spellSlots: {1: 2}},
		3: {totalLevel: 3, spellSlots: {2: 2}, expectResources: {"Channel Divinity": 2}},
		5: {totalLevel: 5, spellSlots: {3: 2}, expectResources: {"Channel Divinity": 2}},
		11: {totalLevel: 11, spellSlots: {6: 1}, expectResources: {"Channel Divinity": 3}},
		17: {totalLevel: 17, spellSlots: {9: 1}, expectResources: {"Channel Divinity": 3}},
		20: {totalLevel: 20, spellSlots: {9: 1}, expectResources: {"Channel Divinity": 4}},
	},
	signatureToggleSkip: {
		skip: true,
		reason: "Time Domain has no persistent toggle unlocked by level 5; its interactive states begin at Cleric 6.",
	},
	featuresMatrix: [
		{
			level: 2,
			untilLevel: 5,
			name: "Channel Divinity",
			kind: "resource",
			resourceMax: 2,
			effects: [{kind: "partialShortRestRestore", resourceName: "Channel Divinity", restoreAmount: 1}],
		},
		{
			level: 3,
			untilLevel: 4,
			name: "Time Domain Spells",
			kind: "spells",
			grantsSpells: ["Gift of Alacrity", "Feather Fall", "Fortune's Favor", "Immovable Object"],
			effects: [
				{kind: "alwaysPreparedSpell", spellName: "Gift of Alacrity", expectedLevel: 1, sourceFeature: "Time Domain Spells", sourceClass: "Cleric"},
				{kind: "alwaysPreparedSpell", spellName: "Feather Fall", expectedLevel: 1, sourceFeature: "Time Domain Spells", sourceClass: "Cleric"},
				{kind: "alwaysPreparedSpell", spellName: "Fortune's Favor", expectedLevel: 2, sourceFeature: "Time Domain Spells", sourceClass: "Cleric"},
				{kind: "alwaysPreparedSpell", spellName: "Immovable Object", expectedLevel: 2, sourceFeature: "Time Domain Spells", sourceClass: "Cleric"},
			],
		},
		{
			level: 3,
			untilLevel: 3,
			name: "Chronological Interference",
			kind: "resource",
			resourceMax: [2, 6],
			effects: [
				{kind: "stateCalc", path: "hasChronologicalInterference", exact: true},
				{kind: "chronologicalInterferenceFlow", featureName: "Chronological Interference"},
			],
		},
		{
			level: 3,
			untilLevel: 3,
			name: "Right on Time",
			kind: "passive",
			effects: [
				{kind: "stateCalc", path: "hasRightOnTime", exact: true},
				{kind: "dynamicInitiativeAbilityBonus", featureName: "Right on Time", ability: "wis"},
			],
		},
		{
			level: 3,
			untilLevel: 3,
			name: "Channel Divinity: Temporal Manipulation",
			kind: "passive",
			effects: [
				{kind: "stateCalc", path: "hasTemporalManipulation", exact: true},
				{kind: "temporalManipulationFlow", featureName: "Channel Divinity: Temporal Manipulation"},
			],
		},
		{
			level: 4,
			name: "Chronological Interference",
			kind: "resource",
			resourceMax: [2, 6],
			effects: [{kind: "stateCalc", path: "hasChronologicalInterference", exact: true}],
		},
		{
			level: 4,
			name: "Right on Time",
			kind: "passive",
			effects: [{kind: "stateCalc", path: "hasRightOnTime", exact: true}],
		},
		{
			level: 4,
			name: "Channel Divinity: Temporal Manipulation",
			kind: "passive",
			effects: [{kind: "stateCalc", path: "hasTemporalManipulation", exact: true}],
		},
		{
			level: 5,
			untilLevel: 6,
			name: "Time Domain Spells",
			kind: "spells",
			grantsSpells: ["Haste", "Slow"],
			effects: [
				{kind: "alwaysPreparedSpell", spellName: "Haste", expectedLevel: 3, sourceFeature: "Time Domain Spells", sourceClass: "Cleric"},
				{kind: "alwaysPreparedSpell", spellName: "Slow", expectedLevel: 3, sourceFeature: "Time Domain Spells", sourceClass: "Cleric"},
			],
		},
		{
			level: 6,
			untilLevel: 17,
			name: "Channel Divinity",
			kind: "resource",
			resourceMax: 3,
			effects: [{kind: "partialShortRestRestore", resourceName: "Channel Divinity", restoreAmount: 1}],
		},
		{
			level: 6,
			untilLevel: 11,
			name: "Eyes of the Future Past",
			kind: "resource",
			resourceMax: [1, 6],
			effects: [
				{kind: "stateCalc", path: "hasEyesOfFuturePast", exact: true},
				{kind: "eyesOfFuturePastFlow", featureName: "Eyes of the Future Past"},
			],
		},
		{
			level: 7,
			untilLevel: 11,
			name: "Time Domain Spells",
			kind: "spells",
			grantsSpells: ["Death Ward", "Freedom of Movement"],
			effects: [
				{kind: "alwaysPreparedSpell", spellName: "Death Ward", expectedLevel: 4, sourceFeature: "Time Domain Spells", sourceClass: "Cleric"},
				{kind: "alwaysPreparedSpell", spellName: "Freedom of Movement", expectedLevel: 4, sourceFeature: "Time Domain Spells", sourceClass: "Cleric"},
			],
		},
		{
			level: 8,
			untilLevel: 11,
			name: "Potent Spellcasting",
			kind: "passive",
			effects: [
				{kind: "stateCalc", path: "hasPotentSpellcasting", exact: true},
				{kind: "cantripDamageBonus", spellName: "Sacred Flame", featureName: "Potent Spellcasting", ability: "wis"},
			],
		},
		{
			level: 9,
			untilLevel: 16,
			name: "Time Domain Spells",
			kind: "spells",
			grantsSpells: ["Temporal Shunt", "Hold Monster"],
			effects: [
				{kind: "alwaysPreparedSpell", spellName: "Temporal Shunt", expectedLevel: 5, sourceFeature: "Time Domain Spells", sourceClass: "Cleric"},
				{kind: "alwaysPreparedSpell", spellName: "Hold Monster", expectedLevel: 5, sourceFeature: "Time Domain Spells", sourceClass: "Cleric"},
			],
		},
		{
			level: 12,
			name: "Eyes of the Future Past",
			kind: "resource",
			resourceMax: [1, 6],
			effects: [{kind: "stateCalc", path: "hasEyesOfFuturePast", exact: true}],
		},
		{
			level: 12,
			name: "Potent Spellcasting",
			kind: "passive",
			effects: [{kind: "stateCalc", path: "hasPotentSpellcasting", exact: true}],
		},
		{
			level: 17,
			untilLevel: 19,
			name: "Time Domain Spells",
			kind: "spells",
			grantsSpells: ["Time Stop", "Time Ravage"],
			effects: [
				{kind: "alwaysPreparedSpell", spellName: "Time Stop", expectedLevel: 9, sourceFeature: "Time Domain Spells", sourceClass: "Cleric"},
				{kind: "alwaysPreparedSpell", spellName: "Time Ravage", expectedLevel: 9, sourceFeature: "Time Domain Spells", sourceClass: "Cleric"},
			],
		},
		{
			level: 17,
			untilLevel: 19,
			name: "Temporal Mastery",
			kind: "passive",
			effects: [
				{kind: "stateCalc", path: "hasTemporalMastery", exact: true},
				{kind: "temporalMasteryAgeFlows", featureName: "Temporal Mastery"},
			],
		},
		{
			level: 18,
			name: "Temporal Mastery",
			kind: "passive",
			effects: [{kind: "stateCalc", path: "hasTemporalMastery", exact: true}],
		},
		{
			level: 18,
			name: "Channel Divinity",
			kind: "resource",
			resourceMax: 4,
			effects: [{kind: "partialShortRestRestore", resourceName: "Channel Divinity", restoreAmount: 1}],
		},
		{
			level: 20,
			name: "Time Domain Spells",
			kind: "spells",
			grantsSpells: [
				"Gift of Alacrity",
				"Feather Fall",
				"Fortune's Favor",
				"Immovable Object",
				"Haste",
				"Slow",
				"Death Ward",
				"Freedom of Movement",
				"Temporal Shunt",
				"Hold Monster",
				"Time Stop",
				"Time Ravage",
			],
			effects: [
				{kind: "alwaysPreparedSpell", spellName: "Gift of Alacrity", expectedLevel: 1, sourceFeature: "Time Domain Spells", sourceClass: "Cleric"},
				{kind: "alwaysPreparedSpell", spellName: "Feather Fall", expectedLevel: 1, sourceFeature: "Time Domain Spells", sourceClass: "Cleric"},
				{kind: "alwaysPreparedSpell", spellName: "Fortune's Favor", expectedLevel: 2, sourceFeature: "Time Domain Spells", sourceClass: "Cleric"},
				{kind: "alwaysPreparedSpell", spellName: "Immovable Object", expectedLevel: 2, sourceFeature: "Time Domain Spells", sourceClass: "Cleric"},
				{kind: "alwaysPreparedSpell", spellName: "Haste", expectedLevel: 3, sourceFeature: "Time Domain Spells", sourceClass: "Cleric"},
				{kind: "alwaysPreparedSpell", spellName: "Slow", expectedLevel: 3, sourceFeature: "Time Domain Spells", sourceClass: "Cleric"},
				{kind: "alwaysPreparedSpell", spellName: "Death Ward", expectedLevel: 4, sourceFeature: "Time Domain Spells", sourceClass: "Cleric"},
				{kind: "alwaysPreparedSpell", spellName: "Freedom of Movement", expectedLevel: 4, sourceFeature: "Time Domain Spells", sourceClass: "Cleric"},
				{kind: "alwaysPreparedSpell", spellName: "Temporal Shunt", expectedLevel: 5, sourceFeature: "Time Domain Spells", sourceClass: "Cleric"},
				{kind: "alwaysPreparedSpell", spellName: "Hold Monster", expectedLevel: 5, sourceFeature: "Time Domain Spells", sourceClass: "Cleric"},
				{kind: "alwaysPreparedSpell", spellName: "Time Stop", expectedLevel: 9, sourceFeature: "Time Domain Spells", sourceClass: "Cleric"},
				{kind: "alwaysPreparedSpell", spellName: "Time Ravage", expectedLevel: 9, sourceFeature: "Time Domain Spells", sourceClass: "Cleric"},
			],
		},
	],
});
